[package]
name = "casiotoy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
ratatui = "0.30.0-alpha.5"
crossterm = "0.29.0"
chrono = "0.4.38"
